set(0,'DefaultAxesFontSize',12);
set(0,'DefaultAxesFontWeight','bold');
%set(0,'DefaultTextFontSize',12);
%set(0,'DefaultTextFontWeight','normal');
%set(0,'DefaultUicontrolFontSize',12);
%set(0,'DefaultUicontrolFontWeight','normal');
%set(0,'DefaultAxesTickLength',[0.02 0.01]);
set(0,'DefaultAxesLineWidth', 1.0);
set(0,'DefaultLineLineWidth', 1.1);
%set(0,'DefaultLineLineWidth', 1);
set(0,'DefaultAxesGridLineStyle','--');
set(0,'DefaultAxesXColor',[0 0 0]);
set(0,'DefaultAxesYColor',[0 0 0]);
